import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  useEffect(() => {
    const handleCredentialResponse = (response: any) => {
      console.log("Encoded JWT ID token: ", response);
    };
    window.onload = () => {
      window.google?.accounts?.id.initialize({
        client_id:
          "580572586668-72l4ppknl7m97hooshhpepm5qruhho3h.apps.googleusercontent.com",
        callback: handleCredentialResponse,
      });
      window?.google?.accounts?.id.renderButton(
        document.getElementById("google-signin-btn") as HTMLElement,
        {
          theme: "outline",
          size: "large",
          type: "standard",
        } // customization attributes
      );
      window.google?.accounts?.id?.prompt(); // also display the One Tap dialog
    };
    return () => {
      window.google?.accounts.id.cancel();
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="google-signin-scope" content="profile email" />
        <meta
          name="google-signin-client_id"
          content={
            "580572586668-72l4ppknl7m97hooshhpepm5qruhho3h.apps.googleusercontent.com"
          }
        />
      </Head>

      <Script
        src="https://accounts.google.com/gsi/client"
        id="gsi-client"
        async
        defer
      />

      <main className={styles.main}>
        <div id="google-signin-btn"></div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
